create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  guest_name text not null,
  attendance text not null default 'si',
  adults integer not null default 0,
  kids integer not null default 0,
  phone text,
  song text,
  message text,
  event_name text,
  event_date text,
  venue text,
  address text
);

alter table public.rsvps enable row level security;

drop policy if exists "Allow public RSVP inserts" on public.rsvps;
create policy "Allow public RSVP inserts"
on public.rsvps
for insert
to anon
with check (true);

drop policy if exists "Allow public RSVP reads" on public.rsvps;
create policy "Allow public RSVP reads"
on public.rsvps
for select
to anon
using (true);
